package com.flightdeal.dao;

import java.math.BigDecimal;
import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

/**
 * DynamoDB bean entity for the FlightPriceHistory table. Maps directly to the table schema with
 * destination as partition key and timestamp as sort key. The lastUpdatedAt field is automatically
 * set by the DynamoDB Enhanced Client on every write.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDbBean
public class PriceRecordEntity {

  public static final String TABLE_NAME = "FlightPriceHistory";

  private String destination;
  private String timestamp;
  private BigDecimal price;
  private String departureDate;
  private String returnDate;
  private String airline;
  private String retrievalTimestamp;
  private Instant lastUpdatedAt;

  @DynamoDbPartitionKey
  public String getDestination() {
    return destination;
  }

  @DynamoDbSortKey
  public String getTimestamp() {
    return timestamp;
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getLastUpdatedAt() {
    return lastUpdatedAt;
  }
}
