package com.flightdeal.dao;

import java.time.Instant;
import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import software.amazon.awssdk.enhanced.dynamodb.extensions.annotations.DynamoDbAutoGeneratedTimestampAttribute;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbBean;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbPartitionKey;
import software.amazon.awssdk.enhanced.dynamodb.mapper.annotations.DynamoDbSortKey;

/**
 * DynamoDB bean entity for the FlightPriceHistory table. Stores flight deal data from the SerpApi
 * Google Flights API response. Partition key: route (e.g. "JFK-CDG"), Sort key: timestamp.
 */
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
@DynamoDbBean
public class PriceRecordEntity {

  public static final String TABLE_NAME = "FlightPriceHistory";

  /** Route as "DEPARTURE-ARRIVAL" (e.g. "JFK-CDG") — partition key */
  private String route;

  /** ISO-8601 timestamp of when this record was stored — sort key */
  private String timestamp;

  /** Ticket price in EUR */
  private Integer price;

  /** Departure airport IATA code */
  private String departureAirportId;

  /** Departure airport name */
  private String departureAirportName;

  /** Departure time from the first flight segment */
  private String departureTime;

  /** Arrival airport IATA code */
  private String arrivalAirportId;

  /** Arrival airport name */
  private String arrivalAirportName;

  /** Arrival time from the last flight segment */
  private String arrivalTime;

  /** Primary airline name */
  private String airline;

  /** Total trip duration in minutes */
  private Integer totalDuration;

  /** Number of flight segments (1 = direct) */
  private Integer segments;

  /** Flight number of the first segment */
  private String flightNumber;

  /** Flight type: "best" or "other" */
  private String dealType;

  /** Carbon emissions in grams for this flight */
  private Integer carbonEmissions;

  /** Outbound date searched (YYYY-MM-DD) */
  private String outboundDate;

  /** Return date searched (YYYY-MM-DD) */
  private String returnDate;

  /** Auto-generated timestamp on every write */
  private Instant lastUpdatedAt;

  @DynamoDbPartitionKey
  public String getRoute() {
    return route;
  }

  @DynamoDbSortKey
  public String getTimestamp() {
    return timestamp;
  }

  @DynamoDbAutoGeneratedTimestampAttribute
  public Instant getLastUpdatedAt() {
    return lastUpdatedAt;
  }
}
