package com.flightdeal.guice;

import com.flightdeal.config.AppConfigClient;
import com.flightdeal.config.FlightSearchConfig;
import com.flightdeal.dao.DynamoDbPriceRecordDao;
import com.flightdeal.dao.PriceRecordDao;
import com.flightdeal.metrics.MetricsEmitter;
import com.flightdeal.proxy.FlightApiClient;
import com.google.inject.AbstractModule;
import com.google.inject.Provides;
import com.google.inject.Singleton;
import com.google.inject.name.Named;
import software.amazon.awssdk.enhanced.dynamodb.DynamoDbEnhancedClient;
import software.amazon.awssdk.enhanced.dynamodb.extensions.AutoGeneratedTimestampRecordExtension;
import software.amazon.awssdk.services.cloudwatch.CloudWatchClient;
import software.amazon.awssdk.services.dynamodb.DynamoDbClient;
import software.amazon.awssdk.services.secretsmanager.SecretsManagerClient;
import software.amazon.awssdk.services.secretsmanager.model.GetSecretValueRequest;
import software.amazon.awssdk.services.sns.SnsClient;

/**
 * Guice module for the Flight Search Lambda handler. Reads API key from Secrets Manager and config
 * from AppConfig.
 */
public class FlightSearchModule extends AbstractModule {

  @Override
  protected void configure() {
    bind(PriceRecordDao.class).to(DynamoDbPriceRecordDao.class).in(Singleton.class);
  }

  @Provides
  @Singleton
  FlightApiClient provideFlightApiClient(SecretsManagerClient secretsClient) {
    String secretName = System.getenv("SERPAPI_SECRET_NAME");
    if (secretName == null || secretName.isBlank()) {
      secretName = "serpapi-key";
    }
    String apiKey =
        secretsClient
            .getSecretValue(GetSecretValueRequest.builder().secretId(secretName).build())
            .secretString();
    return new FlightApiClient(apiKey);
  }

  @Provides
  @Singleton
  SecretsManagerClient provideSecretsManagerClient() {
    return SecretsManagerClient.create();
  }

  @Provides
  @Singleton
  AppConfigClient provideAppConfigClient() {
    return new AppConfigClient();
  }

  @Provides
  @Singleton
  FlightSearchConfig provideFlightSearchConfig(AppConfigClient appConfigClient) {
    return appConfigClient.fetchConfig();
  }

  @Provides
  @Singleton
  DynamoDbClient provideDynamoDbClient() {
    return DynamoDbClient.create();
  }

  @Provides
  @Singleton
  DynamoDbEnhancedClient provideDynamoDbEnhancedClient(DynamoDbClient dynamoDbClient) {
    return DynamoDbEnhancedClient.builder()
        .dynamoDbClient(dynamoDbClient)
        .extensions(AutoGeneratedTimestampRecordExtension.create())
        .build();
  }

  @Provides
  @Singleton
  SnsClient provideSnsClient() {
    return SnsClient.create();
  }

  @Provides
  @Singleton
  CloudWatchClient provideCloudWatchClient() {
    return CloudWatchClient.create();
  }

  @Provides
  @Singleton
  MetricsEmitter provideMetricsEmitter(CloudWatchClient cloudWatchClient) {
    return new MetricsEmitter(cloudWatchClient);
  }

  @Provides
  @Named("TOPIC_ARN")
  String provideTopicArn() {
    return System.getenv("TOPIC_ARN");
  }
}
